# Generated by Django 4.2.1 on 2025-01-08 22:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('number_of_mens', models.IntegerField(default=0, verbose_name="Number of Men's")),
                ('number_of_women', models.IntegerField(default=0, verbose_name="Number of Women's")),
                ('number_of_youth', models.IntegerField(default=0, verbose_name="Number of Youth's")),
                ('number_of_children', models.IntegerField(default=0, verbose_name="Number of Children's")),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Service Attendance',
                'verbose_name_plural': 'Service Attendance',
                'ordering': ('date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=205, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('telephone', models.CharField(default='000000', max_length=255, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('postcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Postcode')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='House Number')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('sex', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True)),
                ('department', models.CharField(blank=True, choices=[('MEN', "Men's Ministry"), ('WOMEN', 'Women Ministry'), ('YOUTH', 'Youth Ministry'), ('CHILDREN', 'Children Ministry')], max_length=255, null=True, verbose_name='Department')),
                ('member_type', models.CharField(blank=True, choices=[('FULL MEMBER', 'Full Member'), ('VISITOR', 'Visitor')], default='Full Member', max_length=255, null=True, verbose_name='Member type')),
                ('origin', models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('IMPORT', 'Import'), ('MANUAL', 'Manual')], default='Manual', max_length=255, null=True, verbose_name='Origin')),
                ('membership_start', models.DateField(blank=True, max_length=255, null=True, verbose_name='Membership start')),
                ('last_seen', models.DateField(auto_now_add=True, null=True, verbose_name='Last seen')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Members',
                'ordering': ('name', 'surname', 'member_type', 'postcode', 'origin', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ServicePlanning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Sunday Service', max_length=255, verbose_name='Title')),
                ('service_type', models.CharField(choices=[('01-SERVICE', '1st Service'), ('02-SERVICE', '2nd Service'), ('03-SERVICE', '3rd Service')], max_length=255, verbose_name='Service Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('mc', models.CharField(blank=True, max_length=255, null=True, verbose_name='MC')),
                ('mc_start_time', models.TimeField(blank=True, null=True, verbose_name='MC Start Time')),
                ('mc_end_time', models.TimeField(blank=True, null=True, verbose_name='MC End Time')),
                ('expected_mc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected MC')),
                ('expected_mc_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected MC Start Time')),
                ('expected_mc_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected MC End Time')),
                ('worship_praise', models.CharField(blank=True, max_length=255, null=True, verbose_name='Worship and Praise')),
                ('worship_praise_start_time', models.TimeField(blank=True, null=True, verbose_name='Worship and Praise Start Time')),
                ('worship_praise_end_time', models.TimeField(blank=True, null=True, verbose_name='Worship and Praise End Time')),
                ('expected_worship_praise', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Worship and Praise')),
                ('expected_worship_praise_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected Worship and Praise Time')),
                ('expected_worship_praise_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected Worship and Praise End Time')),
                ('bible_reading', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bible Reading')),
                ('bible_reading_start_time', models.TimeField(blank=True, null=True, verbose_name='Bible Reading Start Time')),
                ('bible_reading_end_time', models.TimeField(blank=True, null=True, verbose_name='Bible Reading End Time')),
                ('expected_bible_reading', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Bible Reading')),
                ('expected_bible_reading_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected Bible Reading Start Time')),
                ('expected_bible_reading_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected Bible Reading End Time')),
                ('mtag_news', models.CharField(blank=True, max_length=255, null=True, verbose_name='MTAG news')),
                ('mtag_news_start_time', models.TimeField(blank=True, null=True, verbose_name='MTAG news Start Time')),
                ('mtag_news_end_time', models.TimeField(blank=True, null=True, verbose_name='MTAG news End Time')),
                ('expected_mtag_news', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected MTAG news')),
                ('expected_mtag_news_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected MTAG news Start Time')),
                ('expected_mtag_news_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected MTAG news End Time')),
                ('offering_ministration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Offering & Ministration')),
                ('offering_ministration_start_time', models.TimeField(blank=True, null=True, verbose_name='Offering & Ministration Start Time')),
                ('offering_ministration_end_time', models.TimeField(blank=True, null=True, verbose_name='Offering & Ministration End Time')),
                ('expected_offering_ministration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Offering & Ministration')),
                ('expected_offering_ministration_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected Offering & Ministration Start Time')),
                ('expected_offering_ministration_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected Offering & Ministration End Time')),
                ('sermon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sermon')),
                ('sermon_start_time', models.TimeField(blank=True, null=True, verbose_name='Sermon Start Time')),
                ('sermon_end_time', models.TimeField(blank=True, null=True, verbose_name='Sermon End Time')),
                ('expected_sermon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Sermon')),
                ('expected_sermon_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected Sermon Start Time')),
                ('expected_sermon_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected Sermon End Time')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Report')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Service Planning',
                'ordering': ('service_type', 'date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_phone_number', models.CharField(max_length=255, verbose_name='Contact Phone Number')),
                ('last_seen', models.DateField(verbose_name='Last seen')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('source', models.CharField(blank=True, choices=[('IMPORT', 'Import'), ('MANUAL', 'Manual')], default='IMPORT', max_length=255, null=True, verbose_name='Source')),
                ('contacted', models.BooleanField(default=False, verbose_name='Contacted')),
                ('contacted_date', models.DateField(blank=True, null=True, verbose_name='Contacted Date')),
                ('person_of_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Person of contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_member', to='servicemanagement.member')),
            ],
            options={
                'verbose_name_plural': 'Member Absence',
                'ordering': ('member', 'created_at'),
            },
        ),
    ]
