# Generated by Django 4.2.1 on 2024-02-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone')),
                ('postcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Postcode')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='House Number')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('sex', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True)),
                ('department', models.CharField(blank=True, choices=[('MEN', "Men's Ministry"), ('WOMEN', 'Women Ministry'), ('YOUTH', 'Youth Ministry'), ('CHILDREN', 'Children Ministry')], max_length=255, null=True, verbose_name='Department')),
                ('member_type', models.CharField(blank=True, choices=[('FULL MEMBER', 'Full Member'), ('VISITOR', 'Visitor')], default='Full Member', max_length=255, null=True, verbose_name='Member type')),
                ('origin', models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('IMPORT', 'Import'), ('MANUAL', 'Manual')], default='Manual', max_length=255, null=True, verbose_name='Origin')),
                ('membership_start', models.DateField(blank=True, max_length=255, null=True, verbose_name='Membership start')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Members',
                'ordering': ('name', 'surname', 'member_type', 'postcode', 'origin', 'created_at'),
            },
        ),
    ]
