# Generated by Django 4.2.1 on 2024-02-04 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlanning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Sunday Service', max_length=255, verbose_name='Title')),
                ('service_type', models.CharField(choices=[('01-SERVICE', '1st Service'), ('02-SERVICE', '2nd Service')], max_length=255, verbose_name='Service Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('mc', models.CharField(blank=True, max_length=255, null=True, verbose_name='MC')),
                ('mc_start_time', models.TimeField(blank=True, null=True, verbose_name='MC Start Time')),
                ('mc_end_time', models.TimeField(blank=True, null=True, verbose_name='MC End Time')),
                ('expected_mc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected MC')),
                ('expected_mc_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected MC Start Time')),
                ('expected_mc_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected MC End Time')),
                ('worship_praise', models.CharField(blank=True, max_length=255, null=True, verbose_name='Worship and Praise')),
                ('worship_praise_start_time', models.TimeField(blank=True, null=True, verbose_name='Worship and Praise Start Time')),
                ('worship_praise_end_time', models.TimeField(blank=True, null=True, verbose_name='Worship and Praise End Time')),
                ('expected_worship_praise', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Worship and Praise')),
                ('expected_worship_praise_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected Worship and Praise Time')),
                ('expected_worship_praise_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected Worship and Praise End Time')),
                ('bible_reading', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bible Reading')),
                ('bible_reading_start_time', models.TimeField(blank=True, null=True, verbose_name='Bible Reading Start Time')),
                ('bible_reading_end_time', models.TimeField(blank=True, null=True, verbose_name='Bible Reading End Time')),
                ('expected_bible_reading', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Bible Reading')),
                ('expected_bible_reading_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected Bible Reading Start Time')),
                ('expected_bible_reading_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected Bible Reading End Time')),
                ('mtag_news', models.CharField(blank=True, max_length=255, null=True, verbose_name='MTAG news')),
                ('mtag_news_start_time', models.TimeField(blank=True, null=True, verbose_name='MTAG news Start Time')),
                ('mtag_news_end_time', models.TimeField(blank=True, null=True, verbose_name='MTAG news End Time')),
                ('expected_mtag_news', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected MTAG news')),
                ('expected_mtag_news_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected MTAG news Start Time')),
                ('expected_mtag_news_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected MTAG news End Time')),
                ('offering_ministration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Offering & Ministration')),
                ('offering_ministration_start_time', models.TimeField(blank=True, null=True, verbose_name='Offering & Ministration Start Time')),
                ('offering_ministration_end_time', models.TimeField(blank=True, null=True, verbose_name='Offering & Ministration End Time')),
                ('expected_offering_ministration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Offering & Ministration')),
                ('expected_offering_ministration_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected Offering & Ministration Start Time')),
                ('expected_offering_ministration_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected Offering & Ministration End Time')),
                ('sermon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sermon')),
                ('sermon_start_time', models.TimeField(blank=True, null=True, verbose_name='Sermon Start Time')),
                ('sermon_end_time', models.TimeField(blank=True, null=True, verbose_name='Sermon End Time')),
                ('expected_sermon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Sermon')),
                ('expected_sermon_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected Sermon Start Time')),
                ('expected_sermon_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected Sermon End Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Service',
                'ordering': ('service_type', 'date', 'created_at'),
            },
        ),
    ]
