# Generated by Django 4.2.1 on 2025-01-08 19:08

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0003_serviceplanning_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, verbose_name='Name')),
        ),
    ]
