# Generated by Django 4.2.1 on 2024-02-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0003_serviceplanning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceplanning',
            options={'ordering': ('service_type', 'date', 'created_at'), 'verbose_name_plural': 'Service Planning'},
        ),
    ]
