# Generated by Django 4.2.1 on 2025-01-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0003_serviceplanning_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=205, verbose_name='First Name'),
        ),
    ]
