# Generated by Django 4.2.1 on 2025-01-08 21:29

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0004_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=django_cryptography.fields.encrypt(models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, null=True)),
        ),
        migrations.AlterField(
            model_name='member',
            name='house_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True, verbose_name='House Number')),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
        ),
        migrations.AlterField(
            model_name='member',
            name='postcode',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='Postcode')),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, verbose_name='Surname')),
        ),
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=django_cryptography.fields.encrypt(models.CharField(default='000000', max_length=255, verbose_name='Telephone')),
        ),
    ]
