# Generated by Django 4.2.1 on 2024-02-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0004_alter_serviceplanning_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_seen',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Last seen'),
        ),
    ]
