# Generated by Django 4.2.1 on 2025-01-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0005_alter_member_address_alter_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='House Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=models.CharField(default='000000', max_length=255, verbose_name='Telephone'),
        ),
    ]
