# Generated by Django 4.2.1 on 2024-02-06 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0006_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='contacted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contacted Date'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicemanagement.member'),
        ),
    ]
