# Generated by Django 4.2.1 on 2024-02-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0008_alter_absence_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_member', to='servicemanagement.member'),
        ),
    ]
