# Generated by Django 4.2.1 on 2024-02-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0009_alter_absence_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='member',
            field=models.CharField(max_length=255, verbose_name='dfd Phone Number'),
        ),
    ]
