# Generated by Django 4.2.1 on 2024-02-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0011_alter_absence_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='source',
            field=models.CharField(blank=True, choices=[('IMPORT', 'Import'), ('MANUAL', 'Manual')], default='Manual', max_length=255, null=True, verbose_name='Source'),
        ),
    ]
