# Generated by Django 4.2.1 on 2024-02-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0014_alter_absence_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
