# Generated by Django 4.2.1 on 2024-02-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0015_member_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='archived',
        ),
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
