# Generated by Django 4.2.1 on 2024-04-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0017_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='number_of_children',
            field=models.IntegerField(default=0, verbose_name="Number of Children's"),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='number_of_mens',
            field=models.IntegerField(default=0, verbose_name="Number of Men's"),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='number_of_women',
            field=models.IntegerField(default=0, verbose_name="Number of Women's"),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='number_of_youth',
            field=models.IntegerField(default=0, verbose_name="Number of Youth's"),
        ),
    ]
