# Generated by Django 4.2.1 on 2024-08-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0018_alter_attendance_number_of_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=models.CharField(default='000000', max_length=255, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='service_type',
            field=models.CharField(choices=[('01-SERVICE', '1st Service'), ('02-SERVICE', '2nd Service'), ('03-SERVICE', '3rd Service')], max_length=255, verbose_name='Service Type'),
        ),
    ]
