# Generated by Django 4.2.1 on 2024-01-08 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('day', models.CharField(choices=[('01-MONDAY', 'Monday'), ('02-TUESDAY', 'Tuesday'), ('03-WEDNESDAY', 'Wednesday'), ('04-THURSDAY', 'Thursday'), ('05-FRIDAY', 'Friday'), ('06-SATURDAY', 'Saturday'), ('07-SUNDAY', 'Sunday')], max_length=255, verbose_name='Day')),
                ('time', models.TimeField(verbose_name='Time')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Weekly Activities', max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('events', models.ManyToManyField(to='activities.event')),
            ],
            options={
                'verbose_name': 'Weekly Activities',
                'verbose_name_plural': 'Weekly Activities',
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
