# Generated by Django 4.2.1 on 2024-02-04 18:33

import activities.uploadfiles
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', models.TextField(default='', max_length=400, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Long Description')),
                ('day', models.CharField(choices=[('01-MONDAY', 'Monday'), ('02-TUESDAY', 'Tuesday'), ('03-WEDNESDAY', 'Wednesday'), ('04-THURSDAY', 'Thursday'), ('05-FRIDAY', 'Friday'), ('06-SATURDAY', 'Saturday'), ('07-SUNDAY', 'Sunday'), ('08-SUNDAY', 'Sunday 1st Service'), ('09-SUNDAY', 'Sunday 2nd Service')], max_length=255, verbose_name='Day')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('cover_image_path', models.ImageField(blank=True, null=True, upload_to=activities.uploadfiles.event_upload_image_path, validators=[activities.uploadfiles.event_image_restriction], verbose_name='Cover image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', models.TextField(default='', max_length=400, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Long Description')),
                ('speaker', models.CharField(blank=True, max_length=255, null=True, verbose_name='speaker')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('cover_image_path', models.ImageField(blank=True, null=True, upload_to=activities.uploadfiles.event_upload_image_path, validators=[activities.uploadfiles.event_image_restriction], verbose_name='Cover image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Weekly Activities', max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('events', models.ManyToManyField(to='activities.event')),
            ],
            options={
                'verbose_name': 'Weekly Activities',
                'verbose_name_plural': 'Weekly Activities',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Monthly Activities', max_length=255, verbose_name='Title')),
                ('month', models.CharField(choices=[('01-JANUARY', 'January'), ('02-FEBRUARY', 'February'), ('03-MARCH', 'March'), ('04-APRIL', 'April'), ('05-MAY', 'May'), ('06-JUNE', 'June'), ('07-JULY', 'July'), ('08-AUGUST', 'August'), ('09-SEPTEMBER', 'September'), ('10-OCTOBER', 'October'), ('11-NOVEMBER', 'November'), ('12-DECEMBER', 'December')], max_length=255, verbose_name='Month')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('programs', models.ManyToManyField(to='activities.program')),
            ],
            options={
                'verbose_name': 'Monthly Activities',
                'verbose_name_plural': 'Monthly Activities',
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
