# Generated by Django 4.2.1 on 2024-03-26 18:26

import activities.uploadfiles
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', models.TextField(default='', max_length=400, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Long Description')),
                ('day', models.CharField(choices=[('01-MONDAY', 'Monday'), ('02-TUESDAY', 'Tuesday'), ('03-WEDNESDAY', 'Wednesday'), ('04-THURSDAY', 'Thursday'), ('05-FRIDAY', 'Friday'), ('06-SATURDAY', 'Saturday'), ('07-SUNDAY', 'Sunday'), ('08-SUNDAY', 'Sunday 1st Service'), ('09-SUNDAY', 'Sunday 2nd Service')], max_length=255, verbose_name='Day')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('cover_image_path', models.ImageField(blank=True, null=True, upload_to=activities.uploadfiles.event_upload_image_path, validators=[activities.uploadfiles.event_image_restriction], verbose_name='Cover image')),
                ('gallery_image_path_1', models.ImageField(blank=True, null=True, upload_to=activities.uploadfiles.event_upload_image_path, validators=[activities.uploadfiles.event_image_restriction], verbose_name='Gallery image 1')),
                ('gallery_image_path_2', models.ImageField(blank=True, null=True, upload_to=activities.uploadfiles.event_upload_image_path, validators=[activities.uploadfiles.event_image_restriction], verbose_name='Gallery image 2')),
                ('gallery_image_path_3', models.ImageField(blank=True, null=True, upload_to=activities.uploadfiles.event_upload_image_path, validators=[activities.uploadfiles.event_image_restriction], verbose_name='Gallery image 3')),
                ('gallery_image_path_4', models.ImageField(blank=True, null=True, upload_to=activities.uploadfiles.event_upload_image_path, validators=[activities.uploadfiles.event_image_restriction], verbose_name='Gallery image 4')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
