# Generated by Django 4.2.1 on 2024-03-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_socialevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialevent',
            options={'ordering': ('title', 'created_at'), 'verbose_name': 'Social Events', 'verbose_name_plural': 'Social Events'},
        ),
    ]
