# Generated by Django 4.2.1 on 2024-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_event_day_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='socialevent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='socialevent',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short Description'),
        ),
    ]
