# Generated by Django 4.2.1 on 2024-01-08 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Monthly Activities', max_length=255, verbose_name='Title')),
                ('month', models.CharField(choices=[('01-JANUARY', 'January'), ('02-FEBRUARY', 'February'), ('03-MARCH', 'March'), ('04-APRIL', 'April'), ('05-MAY', 'May'), ('06-JUNE', 'June'), ('07-JULY', 'July'), ('08-AUGUST', 'August'), ('09-SEPTEMBER', 'September'), ('10-OCTOBER', 'October'), ('11-NOVEMBER', 'November'), ('12-DECEMBER', 'December')], max_length=255, verbose_name='Month')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('events', models.ManyToManyField(to='activities.event')),
            ],
            options={
                'verbose_name': 'Monthly Activities',
                'verbose_name_plural': 'Monthly Activities',
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
