# Generated by Django 4.2.1 on 2024-01-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_event_date_remove_event_time_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(blank=True, choices=[('01-MONDAY', 'Monday'), ('02-TUESDAY', 'Tuesday'), ('03-WEDNESDAY', 'Wednesday'), ('04-THURSDAY', 'Thursday'), ('05-FRIDAY', 'Friday'), ('06-SATURDAY', 'Saturday'), ('07-SUNDAY', 'Sunday')], max_length=255, null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
