# Generated by Django 4.2.1 on 2024-01-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_event_end_time_event_start_time_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(default='', max_length=1024, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Long Description'),
        ),
    ]
