# Generated by Django 4.2.1 on 2024-01-18 13:14

import activities.uploadfiles
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_alter_event_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', models.TextField(default='', max_length=400, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Long Description')),
                ('speaker', models.CharField(blank=True, max_length=255, null=True, verbose_name='speaker')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('cover_image_path', models.ImageField(blank=True, null=True, upload_to=activities.uploadfiles.event_upload_image_path, verbose_name='Cover image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.RemoveField(
            model_name='monthly',
            name='events',
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(blank=True, choices=[('01-MONDAY', 'Monday'), ('02-TUESDAY', 'Tuesday'), ('03-WEDNESDAY', 'Wednesday'), ('04-THURSDAY', 'Thursday'), ('05-FRIDAY', 'Friday'), ('06-SATURDAY', 'Saturday'), ('07-SUNDAY', 'Sunday'), ('08-SUNDAY', 'Sunday 1st Service'), ('09-SUNDAY', 'Sunday 2nd Service')], max_length=255, null=True, verbose_name='Day'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='programs',
            field=models.ManyToManyField(to='activities.program'),
        ),
    ]
