# Generated by Django 4.2.1 on 2024-01-20 23:05

import activities.uploadfiles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_program_remove_monthly_events_alter_event_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=activities.uploadfiles.event_upload_image_path, validators=[activities.uploadfiles.event_image_restriction], verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(choices=[('01-MONDAY', 'Monday'), ('02-TUESDAY', 'Tuesday'), ('03-WEDNESDAY', 'Wednesday'), ('04-THURSDAY', 'Thursday'), ('05-FRIDAY', 'Friday'), ('06-SATURDAY', 'Saturday'), ('07-SUNDAY', 'Sunday'), ('08-SUNDAY', 'Sunday 1st Service'), ('09-SUNDAY', 'Sunday 2nd Service')], default='', max_length=255, verbose_name='Day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='program',
            name='cover_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=activities.uploadfiles.event_upload_image_path, validators=[activities.uploadfiles.event_image_restriction], verbose_name='Cover image'),
        ),
    ]
