# Generated by Django 4.2.1 on 2024-01-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_alter_event_end_time_alter_event_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
