# Generated by Django 4.2.1 on 2024-09-26 19:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=255, verbose_name='Account Number')),
                ('sort_code', models.CharField(max_length=255, verbose_name='Sort code')),
                ('iban', models.CharField(blank=True, max_length=255, verbose_name='IBAN')),
                ('swift_bic', models.CharField(blank=True, max_length=255, verbose_name='SWIFT BIC')),
                ('visible', models.BooleanField(default=False, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Bank Account Details',
                'ordering': ('name', 'account_holder_name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('OFFERING', 'Offering'), ('TITHE', 'Tithe'), ('FREE DONATION', 'Free Donation'), ('OTHER', 'Other')], max_length=255, verbose_name='Type')),
                ('specific_transaction_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Specific transaction type')),
                ('message', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Message')),
                ('service_type', models.CharField(blank=True, choices=[('TUESDAY BIBLE STUDIES', 'Tuesday Bible studies'), ('FRIDAY_PRAYER_MEETING', 'Friday Prayer Meeting'), ('1_SUNDAY_SERVICE', 'Sunday 1st Service'), ('2_SUNDAY_SERVICE', 'Sunday 2nd Service'), ('3_SUNDAY_SERVICE', 'Sunday 3rd Service')], max_length=255, null=True, verbose_name='Service Type')),
                ('date', models.DateField(max_length=255, verbose_name='Date')),
                ('month', models.CharField(choices=[('01-JANUARY', 'January'), ('02-FEBRUARY', 'February'), ('03-MARCH', 'March'), ('04-APRIL', 'April'), ('05-MAY', 'May'), ('06-JUNE', 'June'), ('07-JULY', 'July'), ('08-AUGUST', 'August'), ('09-SEPTEMBER', 'September'), ('10-OCTOBER', 'October'), ('11-NOVEMBER', 'November'), ('12-DECEMBER', 'December')], editable=False, max_length=255, verbose_name='Month')),
                ('source', models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('BANK TRANSFER', 'Bank Transfer'), ('MANUAL', 'Manual')], default='Manual', max_length=255, null=True, verbose_name='Source')),
                ('opted_in_gift_aid_donation', models.BooleanField(default=False, verbose_name='Opted in gift aid donation')),
                ('gift_aid_donation_occurence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gift aid donation occurence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='servicemanagement.member')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ('type', 'created_at'),
            },
        ),
    ]
