# Generated by Django 4.2.1 on 2024-02-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='month',
            field=models.CharField(choices=[('01-JANUARY', 'January'), ('02-FEBRUARY', 'February'), ('03-MARCH', 'March'), ('04-APRIL', 'April'), ('05-MAY', 'May'), ('06-JUNE', 'June'), ('07-JULY', 'July'), ('08-AUGUST', 'August'), ('09-SEPTEMBER', 'September'), ('10-OCTOBER', 'October'), ('11-NOVEMBER', 'November'), ('12-DECEMBER', 'December')], editable=False, max_length=255, verbose_name='Month'),
        ),
    ]
