# Generated by Django 4.2.1 on 2024-02-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='specific_transaction_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specific transaction type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('OFFERING', 'Offering'), ('TITHE', 'Tithe'), ('FREE DONATION', 'Free Donation'), ('OTHER', 'Other')], max_length=255, verbose_name='Type'),
        ),
    ]
