# Generated by Django 4.2.1 on 2024-03-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_specific_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gift_aid_donation_occurence',
            field=models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('BANK TRANSFER', 'Bank Transfer'), ('MANUAL', 'Manual')], max_length=255, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='opted_in_gift_aid_donation',
            field=models.BooleanField(default=False, verbose_name='Opted in gift aid donation'),
        ),
    ]
