# Generated by Django 4.2.1 on 2024-03-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction_gift_aid_donation_occurence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gift_aid_donation_occurence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source'),
        ),
    ]
