# Generated by Django 4.2.1 on 2024-03-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaction_gift_aid_donation_occurence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gift_aid_donation_occurence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gift aid donation occurence'),
        ),
    ]
