# Generated by Django 4.2.1 on 2024-08-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_transaction_gift_aid_donation_occurence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(blank=True, choices=[('TUESDAY BIBLE STUDIES', 'Tuesday Bible studies'), ('FRIDAY_PRAYER_MEETING', 'Friday Prayer Meeting'), ('1_SUNDAY_SERVICE', 'Sunday 1st Service'), ('2_SUNDAY_SERVICE', 'Sunday 2nd Service'), ('3_SUNDAY_SERVICE', 'Sunday 3rd Service')], max_length=255, null=True, verbose_name='Service Type'),
        ),
    ]
