# Generated by Django 4.2.1 on 2024-02-04 18:42

from django.db import migrations, models
import ministries.uploadfiles
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('short_description', models.TextField(default='', max_length=400, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Long Description')),
                ('cover_image_path', models.ImageField(upload_to=ministries.uploadfiles.ministries_upload_image_path, validators=[ministries.uploadfiles.ministry_cover_image_restriction], verbose_name='Cover image')),
                ('gallery_image_path_1', models.ImageField(blank=True, null=True, upload_to=ministries.uploadfiles.ministries_upload_image_path, validators=[ministries.uploadfiles.ministry_gallery_image_restriction], verbose_name='Gallery image 1')),
                ('gallery_image_path_2', models.ImageField(blank=True, null=True, upload_to=ministries.uploadfiles.ministries_upload_image_path, validators=[ministries.uploadfiles.ministry_gallery_image_restriction], verbose_name='Gallery image 2')),
                ('gallery_image_path_3', models.ImageField(blank=True, null=True, upload_to=ministries.uploadfiles.ministries_upload_image_path, validators=[ministries.uploadfiles.ministry_gallery_image_restriction], verbose_name='Gallery image 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Ministries',
                'ordering': ('name', 'created_at'),
            },
        ),
    ]
