# Generated by Django 4.2.1 on 2024-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='cover_image_path',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='gallery_image_path_1',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Gallery image 1'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='gallery_image_path_2',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Gallery image 2'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='gallery_image_path_3',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Gallery image 3'),
        ),
    ]
