# Generated by Django 4.2.1 on 2024-01-18 21:31

from django.db import migrations, models
import ministries.uploadfiles


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='cover_image_path',
            field=models.ImageField(upload_to=ministries.uploadfiles.ministries_upload_image_path, verbose_name='Cover image'),
        ),
    ]
