# Generated by Django 4.2.1 on 2024-11-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short Description'),
        ),
    ]
