# Generated by Django 4.2.1 on 2024-11-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0002_alter_ministry_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Index'),
        ),
    ]
