# Generated by Django 4.2.1 on 2024-01-18 21:36

from django.db import migrations, models
import ministries.uploadfiles


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0002_alter_ministry_cover_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='gallery_image_path_2',
            field=models.ImageField(blank=True, null=True, upload_to=ministries.uploadfiles.ministries_upload_image_path, verbose_name='Gallery image 2'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='gallery_image_path_3',
            field=models.ImageField(blank=True, null=True, upload_to=ministries.uploadfiles.ministries_upload_image_path, verbose_name='Gallery image 3'),
        ),
    ]
