# Generated by Django 4.2.1 on 2024-01-20 23:48

from django.db import migrations, models
import ministries.uploadfiles


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0003_ministry_gallery_image_path_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='cover_image_path',
            field=models.ImageField(upload_to=ministries.uploadfiles.ministries_upload_image_path, validators=[ministries.uploadfiles.ministry_cover_image_restriction], verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='gallery_image_path_1',
            field=models.ImageField(blank=True, null=True, upload_to=ministries.uploadfiles.ministries_upload_image_path, validators=[ministries.uploadfiles.ministry_gallery_image_restriction], verbose_name='Gallery image 1'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='gallery_image_path_2',
            field=models.ImageField(blank=True, null=True, upload_to=ministries.uploadfiles.ministries_upload_image_path, validators=[ministries.uploadfiles.ministry_gallery_image_restriction], verbose_name='Gallery image 2'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='gallery_image_path_3',
            field=models.ImageField(blank=True, null=True, upload_to=ministries.uploadfiles.ministries_upload_image_path, validators=[ministries.uploadfiles.ministry_gallery_image_restriction], verbose_name='Gallery image 3'),
        ),
    ]
