# Generated by Django 4.2.1 on 2024-01-11 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlanning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Sunday Service', max_length=255, verbose_name='Title')),
                ('service_type', models.CharField(choices=[('01-SERVICE', '1st Service'), ('02-SERVICE', '2nd Service')], max_length=255, verbose_name='Service Type')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('mc', models.CharField(max_length=255, verbose_name='MC')),
                ('expected_mc', models.CharField(max_length=255, verbose_name='Expected MC')),
                ('worship_praise', models.CharField(max_length=255, verbose_name='Worship and Praise')),
                ('expected_worship_praise', models.CharField(max_length=255, verbose_name='Expected Worship and Praise')),
                ('bible_reading', models.CharField(max_length=255, verbose_name='Bible Reading')),
                ('expected_bible_reading', models.CharField(max_length=255, verbose_name='Expected Bible Reading')),
                ('mtag_news', models.CharField(max_length=255, verbose_name='MTAG news')),
                ('expected_mtag_news', models.CharField(max_length=255, verbose_name='Expected MTAG news')),
                ('offering_ministration', models.CharField(max_length=255, verbose_name='Offering & Ministration')),
                ('expected_offering_ministration', models.CharField(max_length=255, verbose_name='Expected Offering & Ministration')),
                ('sermon', models.CharField(max_length=255, verbose_name='Sermon')),
                ('expected_sermon', models.CharField(max_length=255, verbose_name='Expected Sermon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Service',
                'ordering': ('service_type', 'date', 'created_at'),
            },
        ),
    ]
