# Generated by Django 4.2.1 on 2024-01-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplanning',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
