# Generated by Django 4.2.1 on 2024-01-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_serviceplanning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplanning',
            name='bible_reading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bible Reading'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='expected_bible_reading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Bible Reading'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='expected_mc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected MC'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='expected_mtag_news',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected MTAG news'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='expected_offering_ministration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Offering & Ministration'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='expected_sermon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Sermon'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='expected_worship_praise',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected Worship and Praise'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='mc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MC'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='mtag_news',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MTAG news'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='offering_ministration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Offering & Ministration'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='sermon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sermon'),
        ),
        migrations.AlterField(
            model_name='serviceplanning',
            name='worship_praise',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Worship and Praise'),
        ),
    ]
