# Generated by Django 4.2.1 on 2024-01-19 12:51

from django.db import migrations, models
import homepage.uploadfiles
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to=homepage.uploadfiles.homepage_banner_upload_image_path, verbose_name='Image')),
                ('image_position', models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right')], max_length=255, null=True, verbose_name='Department')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('banners', models.ManyToManyField(to='homepage.banner')),
            ],
        ),
    ]
