# Generated by Django 4.2.1 on 2024-02-04 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='blocks',
        ),
        migrations.AddField(
            model_name='homepage',
            name='blocks',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.block'),
        ),
    ]
