# Generated by Django 4.2.1 on 2024-02-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_homepage_blocks_homepage_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='aboutUs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.aboutus'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blocks',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.block'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.details'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='leadershipBoard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.leadershipboard'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.media'),
        ),
    ]
