# Generated by Django 4.2.1 on 2024-01-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_banner_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('title', 'created_at'), 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ('created_at',), 'verbose_name': 'Homepage', 'verbose_name_plural': 'Homepage'},
        ),
    ]
