# Generated by Django 4.2.1 on 2024-01-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_banner_options_alter_homepage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='Homepage', max_length=255, verbose_name='Title'),
        ),
    ]
