# Generated by Django 4.2.1 on 2024-02-17 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_homepage_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=80, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=180, null=True, verbose_name='Description')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Broadcast',
                'verbose_name_plural': 'Broadcasts',
                'ordering': ('title', 'created_at'),
            },
        ),
    ]
