# Generated by Django 4.2.1 on 2024-01-19 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_homepage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Block Section', max_length=255, verbose_name='Title')),
                ('block_1_title', models.CharField(max_length=255, verbose_name='Block 1 Title')),
                ('block_1_text', models.TextField(max_length=1024, verbose_name='Block 1 Text')),
                ('block_2_title', models.CharField(max_length=255, verbose_name='Block 2 Title')),
                ('block_2_text', models.TextField(max_length=1024, verbose_name='Block 2 Text')),
                ('block_3_title', models.CharField(max_length=255, verbose_name='Block 3 Title')),
                ('block_3_text', models.TextField(max_length=1024, verbose_name='Block 3 Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='blocks',
            field=models.ManyToManyField(to='homepage.block'),
        ),
    ]
