# Generated by Django 4.2.1 on 2024-01-19 18:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_aboutus_homepage_display_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Church Details', max_length=255, verbose_name='Title')),
                ('info_text_1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Info Text 1')),
                ('info_content_1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Info Content 1')),
                ('info_text_2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Info Text 2')),
                ('info_content_2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Info Content 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Details',
                'verbose_name_plural': 'Details',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.details'),
        ),
    ]
