# Generated by Django 4.2.1 on 2024-02-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_remove_broadcast_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcast',
            old_name='StreamDescription',
            new_name='stream_description',
        ),
        migrations.RenameField(
            model_name='broadcast',
            old_name='streamSubtitle',
            new_name='stream_subtitle',
        ),
        migrations.RenameField(
            model_name='broadcast',
            old_name='streamTitle',
            new_name='stream_title',
        ),
    ]
