# Generated by Django 4.2.1 on 2024-01-19 20:26

from django.db import migrations, models
import django.db.models.deletion
import homepage.uploadfiles
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_details_homepage_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=180, null=True, verbose_name='Description')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to=homepage.uploadfiles.homepage_video_cover_upload_image_path, verbose_name='Image')),
                ('url', models.CharField(max_length=255, verbose_name='Url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='homepage_display_info_1_text',
            field=models.TextField(blank=True, max_length=180, null=True, verbose_name='Homepage Display Info 1 Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='homepage_display_info_2_text',
            field=models.TextField(blank=True, max_length=180, null=True, verbose_name='Homepage Display Info 2 Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='homepage_display_text',
            field=models.TextField(max_length=180, verbose_name='Homepage Display Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='section_display_info_1_text',
            field=models.TextField(blank=True, max_length=180, null=True, verbose_name='Section Display Info 1 Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='section_display_info_2_text',
            field=models.TextField(blank=True, max_length=180, null=True, verbose_name='Section Display Info 2 Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='section_display_text',
            field=models.TextField(max_length=180, verbose_name='Section Display Text'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Media', max_length=80, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('videos', models.ManyToManyField(to='homepage.video')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='media',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.media'),
        ),
    ]
