# Generated by Django 4.2.1 on 2024-02-17 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_rename_streamdescription_broadcast_stream_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Social Media Links', max_length=255, verbose_name='Title')),
                ('facebook_link', models.CharField(max_length=255, verbose_name='Facebook Link')),
                ('tiktok_link', models.CharField(max_length=255, verbose_name='Facebook Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.AlterModelOptions(
            name='broadcast',
            options={'ordering': ('title', 'created_at'), 'verbose_name': 'Broadcast', 'verbose_name_plural': 'Broadcast'},
        ),
    ]
