# Generated by Django 4.2.1 on 2024-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_socialmedia_alter_broadcast_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='tiktok_link',
            field=models.CharField(max_length=255, verbose_name='Tik Tok Link'),
        ),
    ]
