# Generated by Django 4.2.1 on 2024-02-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_socialmedia_tiktok_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='address',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='details',
            name='description',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Description'),
        ),
    ]
