# Generated by Django 4.2.1 on 2024-01-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_video_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='videos_header',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Video Section Header'),
        ),
        migrations.AddField(
            model_name='media',
            name='videos_title',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Video Section Title'),
        ),
    ]
