# Generated by Django 4.2.1 on 2024-02-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_details_address_details_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.TextField(blank=True, max_length=280, null=True, verbose_name='Description'),
        ),
    ]
