# Generated by Django 4.2.1 on 2024-01-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_media_videos_header_media_videos_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
