# Generated by Django 4.2.1 on 2024-01-19 22:56

from django.db import migrations, models
import django.db.models.deletion
import homepage.uploadfiles
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_video_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=300, verbose_name='Full Name')),
                ('role', models.CharField(max_length=300, verbose_name='Full Name')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('image', models.ImageField(blank=True, null=True, upload_to=homepage.uploadfiles.homepage_leader_cover_upload_image_path, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Leaders',
                'ordering': ('fullName', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='LeadershipBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Leadership Board', max_length=80, verbose_name='Title')),
                ('header', models.CharField(blank=True, max_length=80, null=True, verbose_name='Section Header')),
                ('section_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Section Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('leaders', models.ManyToManyField(to='homepage.leader')),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Leaders',
                'ordering': ('title', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='leadershipBoard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.leadershipboard'),
        ),
    ]
