# Generated by Django 4.2.1 on 2024-01-20 06:13

from django.db import migrations, models
import homepage.uploadfiles


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_leadershipboard_options_aboutus_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_background_image',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.uploadfiles.homepage_background_upload_image_path, verbose_name='Banner Background Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='leadership_board_background_image',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.uploadfiles.homepage_background_upload_image_path, verbose_name='Leadership Board Background Image'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='section_display_info_1_text',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Section Display Info 1 Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='section_display_info_2_text',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Section Display Info 2 Text'),
        ),
    ]
