# Generated by Django 4.2.1 on 2024-01-20 19:18

from django.db import migrations, models
import homepage.uploadfiles


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_aboutus_homepage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.uploadfiles.homepage_leader_cover_upload_image_path, validators=[homepage.uploadfiles.leader_image_restriction], verbose_name='Image'),
        ),
    ]
