# Generated by Django 4.2.1 on 2023-12-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('telephone', models.CharField(max_length=255, verbose_name='Telephone')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('department', models.CharField(choices=[('MEN', 'Basic'), ('WOMEN', 'Intermediate'), ('YOUTH', 'Advanced')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Members',
                'ordering': ('name', 'created_at'),
            },
        ),
    ]
