# Generated by Django 4.2.1 on 2024-02-04 17:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=255, verbose_name='Account Number')),
                ('sort_code', models.CharField(max_length=255, verbose_name='Sort code')),
                ('iban', models.CharField(blank=True, max_length=255, verbose_name='IBAN')),
                ('swift_bic', models.CharField(blank=True, max_length=255, verbose_name='SWIFT BIC')),
                ('visible', models.BooleanField(default=False, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Bank Account Details',
                'ordering': ('name', 'account_holder_name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone')),
                ('postcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Postcode')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='House Number')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('sex', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True)),
                ('department', models.CharField(blank=True, choices=[('MEN', "Men's Ministry"), ('WOMEN', 'Women Ministry'), ('YOUTH', 'Youth Ministry'), ('CHILDREN', 'Children Ministry')], max_length=255, null=True, verbose_name='Department')),
                ('member_type', models.CharField(blank=True, choices=[('FULL MEMBER', 'Full Member'), ('VISITOR', 'Visitor')], default='Full Member', max_length=255, null=True, verbose_name='Member type')),
                ('origin', models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('IMPORT', 'Import'), ('MANUAL', 'Manual')], default='Manual', max_length=255, null=True, verbose_name='Origin')),
                ('membership_start', models.DateField(blank=True, max_length=255, null=True, verbose_name='Membership start')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Members',
                'ordering': ('name', 'surname', 'member_type', 'postcode', 'origin', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('OFFERING', 'Offering'), ('TITHE', 'Tithe'), ('FREE DONATION', 'Free Donation')], max_length=255, verbose_name='Type')),
                ('message', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Message')),
                ('service_type', models.CharField(blank=True, choices=[('TUESDAY BIBLE STUDIES', 'Tuesday Bible studies'), ('FRIDAY_PRAYER_MEETING', 'Friday Prayer Meeting'), ('1_SUNDAY_SERVICE', 'Sunday 1st Service'), ('2_SUNDAY_SERVICE', 'Sunday 2nd Service')], max_length=255, null=True, verbose_name='Service Type')),
                ('date', models.DateField(max_length=255, verbose_name='Date')),
                ('month', models.CharField(choices=[('01-JANUARY', 'January'), ('02-FEBRUARY', 'February'), ('03-MARCH', 'March'), ('04-APRIL', 'April'), ('05-MAY', 'May'), ('06-JUNE', 'June'), ('07-JULY', 'July'), ('08-AUGUST', 'August'), ('09-SEPTEMBER', 'September'), ('10-OCTOBER', 'October'), ('11-NOVEMBER', 'November'), ('12-DECEMBER', 'December')], max_length=255, verbose_name='Month')),
                ('source', models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('BANK TRANSFER', 'Bank Transfer'), ('MANUAL', 'Manual')], default='Manual', max_length=255, null=True, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.member')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ('type', 'created_at'),
            },
        ),
    ]
