# Generated by Django 4.2.1 on 2023-12-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('MEN', "Men's Ministry"), ('WOMEN', "Children's Ministry"), ('YOUTH', 'Youth Ministry'), ('CHILDREN', 'Children Ministry')], max_length=255),
        ),
    ]
