# Generated by Django 4.2.1 on 2024-02-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(blank=True, choices=[('TUESDAY BIBLE STUDIES', 'Tuesday Bible studies'), ('FRIDAY_PRAYER_MEETING', 'Friday Prayer Meeting'), ('1_SUNDAY_SERVICE', 'Sunday 1st Service'), ('2_SUNDAY_SERVICE', 'Sunday 2nd Service')], max_length=255, null=True, verbose_name='Service Type'),
        ),
    ]
