# Generated by Django 4.2.1 on 2024-01-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('FULL', 'Full Member'), ('VISITOR', 'Visiting Member')], default='Full Member', max_length=255, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_start',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='Membership start'),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('MEN', "Men's Ministry"), ('WOMEN', "Children's Ministry"), ('YOUTH', 'Youth Ministry'), ('CHILDREN', 'Children Ministry')], max_length=255, verbose_name='Department'),
        ),
    ]
