# Generated by Django 4.2.1 on 2024-01-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_member_type_member_membership_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('FULL', 'Full Member'), ('VISITOR', 'Visiting Member')], default='Full Member', max_length=255, verbose_name='Member type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_start',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Membership start'),
        ),
    ]
