# Generated by Django 4.2.1 on 2024-01-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_member_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, choices=[('MEN', "Men's Ministry"), ('WOMEN', "Children's Ministry"), ('YOUTH', 'Youth Ministry'), ('CHILDREN', 'Children Ministry')], max_length=255, null=True, verbose_name='Department'),
        ),
    ]
