# Generated by Django 4.2.1 on 2024-01-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('Full Member', 'Full Member'), ('Visitor', 'Visitor')], default='Full Member', max_length=255, verbose_name='Member type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], max_length=50),
        ),
    ]
