# Generated by Django 4.2.1 on 2024-01-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_address_member_age_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='test',
        ),
    ]
