# Generated by Django 4.2.1 on 2024-01-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='origin',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('IMPORT', 'Import'), ('MANUAL', 'Manual')], default='Manual', max_length=255, verbose_name='Origin'),
        ),
    ]
