# Generated by Django 4.2.1 on 2024-01-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(blank=True, choices=[('FULL MEMBER', 'Full Member'), ('VISITOR', 'Visitor')], default='Full Member', max_length=255, null=True, verbose_name='Member type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True),
        ),
    ]
