# Generated by Django 4.2.1 on 2024-01-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_member_member_type_alter_member_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='origin',
            field=models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('IMPORT', 'Import'), ('MANUAL', 'Manual')], default='Manual', max_length=255, null=True, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone'),
        ),
    ]
