# Generated by Django 4.2.1 on 2024-01-21 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_member_origin_alter_member_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('OFFERING', 'Offering'), ('TITHE', 'Tithe'), ('FREE DONATION', 'Free Donation')], max_length=255, verbose_name='Type')),
                ('date', models.CharField(max_length=255, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ('type', 'created_at'),
            },
        ),
    ]
