# Generated by Django 4.2.1 on 2024-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(blank=True, choices=[('FRIDAY_PRAYER_MEETING', 'Offering'), ('1_SUNDAY_SERVICE', 'Sunday 1st Service'), ('2_SUNDAY_SERVICE', 'Sunday 2nd Service')], max_length=255, null=True, verbose_name='Service Type'),
        ),
    ]
