# Generated by Django 4.2.1 on 2024-01-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_transaction_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.member'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(blank=True, choices=[('FRIDAY_PRAYER_MEETING', 'Friday Prayer Meeting'), ('1_SUNDAY_SERVICE', 'Sunday 1st Service'), ('2_SUNDAY_SERVICE', 'Sunday 2nd Service')], max_length=255, null=True, verbose_name='Service Type'),
        ),
    ]
