# Generated by Django 4.2.1 on 2024-01-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_transaction_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='house_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='House Number'),
        ),
    ]
