# Generated by Django 4.2.1 on 2024-01-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_member_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.CharField(choices=[('FULL MEMBER', 'Full Member'), ('VISITOR', 'Visitor')], default='Full Member', max_length=255, verbose_name='Origin'),
        ),
    ]
