# Generated by Django 4.2.1 on 2024-01-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_transaction_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='origin',
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('IMPORT', 'Import'), ('MANUAL', 'Manual')], default='Manual', max_length=255, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='member',
            name='origin',
            field=models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('BANK TRANSFER', 'Bank Transfer'), ('MANUAL', 'Manual')], default='Manual', max_length=255, null=True, verbose_name='Source'),
        ),
    ]
