# Generated by Django 4.2.1 on 2024-01-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_remove_transaction_origin_transaction_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='origin',
            field=models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('BANK TRANSFER', 'Bank Transfer'), ('MANUAL', 'Manual')], default='Manual', max_length=255, null=True, verbose_name='Origin'),
        ),
    ]
