# Generated by Django 4.2.1 on 2024-01-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_alter_member_origin_alter_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Message'),
        ),
    ]
