# Generated by Django 4.2.1 on 2024-01-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_transaction_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='House Number'),
        ),
    ]
