# Generated by Django 4.2.1 on 2024-01-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_alter_member_house_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('name', 'surname', 'member_type', 'postcode', 'origin', 'created_at'), 'verbose_name_plural': 'Members'},
        ),
    ]
