# Generated by Django 4.2.1 on 2024-01-31 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_alter_member_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='Account Holder Name')),
                ('account_number', models.IntegerField(max_length=255, verbose_name='Account Number')),
                ('sort_code', models.CharField(max_length=255, verbose_name='Sort code')),
                ('iban', models.CharField(blank=True, max_length=255, verbose_name='IBAN')),
                ('swift_bic', models.CharField(blank=True, max_length=255, verbose_name='SWIFT BIC')),
                ('visible', models.BooleanField(default=False, verbose_name='SWIFT BIC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Bank Account Details',
                'ordering': ('name', 'account_holder_name', 'created_at'),
            },
        ),
    ]
