# Generated by Django 4.2.1 on 2024-01-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=255, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
    ]
