# Generated by Django 4.2.1 on 2024-02-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, choices=[('MEN', "Men's Ministry"), ('WOMEN', 'Women Ministry'), ('YOUTH', 'Youth Ministry'), ('CHILDREN', 'Children Ministry')], max_length=255, null=True, verbose_name='Department'),
        ),
    ]
