# Generated by Django 4.2.1 on 2024-02-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_alter_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
    ]
